### ISSUE TITLE
Why do these dates validate?

### ISSUE THREAD

**Issue by mjordan** [unt-libraries/edtf-validate#33]
`190X-5X-8X` and `1900-5X` both validate (as does `1900-51`). What features in the spec allow for those dates? The closest I can see is L2 sub-year groupings, but the month portion of those ends at 41.

**Comment by mjordan** [comment]
Still curious about ^.

**Comment by ldko** [comment]
Hi @mjordan ,
Are you using the most current version of the software? What code are you executing to show them validating?
When I run this code, those dates do not validate for me:
```
>>> from edtf_validate.valid_edtf import is_valid
>>> is_valid('2015-03-05')
True
>>> is_valid('190X-5X-8X')
False
>>> is_valid('1900-5X')
False
>>> is_valid('1900-51')
False
```

**Comment by ldko** [comment]
No need to apologize @mjordan . Glad to hear it is working for you.
